;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        counsel-find-file
        delete-frame
        magit-status
        markdown-outdent-or-delete
        mouse-set-region
        simpleclip-copy
        simpleclip-paste
        swiper-isearch
        yaml-electric-dash-and-dot
        ))
